//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunde : Person
    {
        public string KdNummer { get; set; }
    
        public virtual Mitarbeiter Mitarbeiter { get; set; }
    }
}
